version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  postgres:
    container_name: ${DB_HOST}
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    networks:
      - app-network

  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - .:/var/www/html
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - '0.0.0.0:8080:80'
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public/assets:/home/assets/
    networks:
      - app-network
